In [1]:
import numpy as np 
import open3d as o3d

# pcd = o3d.io.read_point_cloud("C:\\Users\\Username\\Source\\pointcloud\\bunny.pcd")
# out_arr = np.asarray(pcd.points)  
# print("output array from input list : ", out_arr)  

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
pcd = o3d.io.read_point_cloud(r"D:\dataset 10 nuscenes\samples\RADAR_FRONT\n015-2018-11-14-18-57-54+0800__RADAR_FRONT__1542193521787761.pcd")
out_arr = np.asarray(pcd.points)  
print("output array from input list : ", out_arr)  

output array from input list :  [[  1.39999998   2.5          0.        ]
 [  2.          -2.5          0.        ]
 [  2.20000005  -2.5          0.        ]
 [  5.19999981  -3.0999999    0.        ]
 [  5.80000019  -3.0999999    0.        ]
 [  6.          -2.29999995   0.        ]
 [  6.          -3.0999999    0.        ]
 [  5.80000019  -4.0999999    0.        ]
 [  7.19999981  -2.0999999    0.        ]
 [  7.4000001   -2.9000001    0.        ]
 [  7.4000001   -3.0999999    0.        ]
 [ 10.60000038  -2.0999999    0.        ]
 [  6.4000001   12.89999962   0.        ]
 [ 19.60000038   2.29999995   0.        ]
 [ 20.60000038   1.89999998   0.        ]
 [ 21.           5.9000001    0.        ]
 [ 13.80000019 -18.10000038   0.        ]
 [ 24.           1.70000005   0.        ]
 [ 26.20000076   5.9000001    0.        ]
 [ 28.20000076   4.5          0.        ]
 [ 27.60000038  -8.69999981   0.        ]
 [ 29.20000076   0.89999998   0.        ]
 [ 29.           8.69999981   0.        ]
 [

In [3]:
  o3d.visualization.draw_geometries([pcd])

In [4]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [9]:
DATADIR=r"D:\dataset 10 nuscenes\samples"
categories=["RADAR_BACK_LEFT"]

In [10]:
for category in categories:
    path=os.path.join(DATADIR,category)
    c=0
    for img in os.listdir(path):
        if category=="RADAR_BACK_LEFT":
            pcd = o3d.io.read_point_cloud(os.path.join(path,img))
            out_arr = np.asarray(pcd.points)  
            print("output array from input list : ", out_arr)
            o3d.visualization.draw_geometries([pcd])
        if category=="CAM_BACK":
        img_array=cv2.imread(os.path.join(path,img))
        plt.imshow(img_array,cmap="gray")
        plt.show()
        c=c+1;
        if c==10:
            break
    break

output array from input list :  [[ 8.19999981e+00  4.69999981e+00  0.00000000e+00]
 [ 1.01999998e+01  5.50000000e+00  0.00000000e+00]
 [ 1.20000000e+01  6.30000019e+00  0.00000000e+00]
 [ 8.19999981e+00  1.13000002e+01  0.00000000e+00]
 [ 1.53999996e+01  4.30000019e+00  0.00000000e+00]
 [ 6.40000010e+00 -1.53000002e+01  0.00000000e+00]
 [ 1.20000000e+01  1.25000000e+01  0.00000000e+00]
 [ 1.90000000e+01  6.30000019e+00  0.00000000e+00]
 [ 1.96000004e+01 -1.06999998e+01  0.00000000e+00]
 [ 2.00000000e+01 -1.08999996e+01  0.00000000e+00]
 [ 2.30000000e+01  8.30000019e+00  0.00000000e+00]
 [ 2.82000008e+01  5.90000010e+00  0.00000000e+00]
 [ 2.96000004e+01  9.30000019e+00  0.00000000e+00]
 [ 2.57999992e+01 -1.97000008e+01  0.00000000e+00]
 [ 3.17999992e+01  9.50000000e+00  0.00000000e+00]
 [ 2.72000008e+01 -2.01000004e+01  0.00000000e+00]
 [ 2.96000004e+01  1.58999996e+01  0.00000000e+00]
 [ 3.30000000e+01  9.30000019e+00  0.00000000e+00]
 [ 2.90000000e+01  1.82999992e+01  0.00000000e+00]